services:
  - type: web
    name: emotion-detector
    env: python
    plan: free
    branch: main
    repo: https://github.com/csmishra952/Emotion-Detector
    buildCommand: |
      pip install -r requirements.txt gunicorn
      # Add commands to download models, e.g.:
      # python -m scripts.download_model
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        sync: false
